os:
  - linux
  - osx

osx_image: xcode11

sudo: required

dist: xenial

language: cpp

services:
  - postgresql
  
addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    - sourceline: 'ppa:mhier/libboost-latest'
    packages:
    - gcc
    - g++
    - libjsoncpp-dev
    - uuid-dev
    - zlib1g-dev
    - postgresql-server-dev-10
    - openssl
    - libssl-dev
    - libsqlite3-dev
    - build-essential
    - cmake
    - boost1.67
  homebrew:
    packages:
    - jsoncpp
    - ossp-uuid
    - openssl
    - cmake
    - libtool
    - lz4
    - mariadb
    - sqlite3
    update: true
script:
  - ./build.sh -t && ./test.sh -t
